# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/zybo_breakout.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}]

# IP: bd/system/ip/system_affine_transform_0_0/system_affine_transform_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_affine_transform_0_0 || ORIG_REF_NAME==system_affine_transform_0_0}]

# IP: bd/system/ip/system_vga_sync_0_0/system_vga_sync_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga_sync_0_0 || ORIG_REF_NAME==system_vga_sync_0_0}]

# IP: bd/system/ip/system_vga_color_test_0_0/system_vga_color_test_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga_color_test_0_0 || ORIG_REF_NAME==system_vga_color_test_0_0}]

# IP: bd/system/ip/system_zybo_hdmi_0_0/system_zybo_hdmi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_zybo_hdmi_0_0 || ORIG_REF_NAME==system_zybo_hdmi_0_0}]

# IP: bd/system/ip/system_inverter_0_0/system_inverter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_inverter_0_0 || ORIG_REF_NAME==system_inverter_0_0}]

# IP: bd/system/ip/system_affine_rotation_generator_0_0/system_affine_rotation_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_affine_rotation_generator_0_0 || ORIG_REF_NAME==system_affine_rotation_generator_0_0}]

# XDC: bd/system/system_ooc.xdc
