# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/Rob/Documents/Class/ECEC662/zybo-toolbox/video_processing_ip/rgb888_to_rgb565/rgb888_to_rgb565.cache/wt [current_project]
set_property parent.project_path D:/Users/Rob/Documents/Class/ECEC662/zybo-toolbox/video_processing_ip/rgb888_to_rgb565/rgb888_to_rgb565.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib D:/Users/Rob/Documents/Class/ECEC662/zybo-toolbox/video_processing_ip/rgb888_to_rgb565/rgb888_to_rgb565.srcs/sources_1/new/rgb888_to_rgb565.vhd
synth_design -top rgb888_to_rgb565 -part xc7z010clg400-1
write_checkpoint -noxdef rgb888_to_rgb565.dcp
catch { report_utilization -file rgb888_to_rgb565_utilization_synth.rpt -pb rgb888_to_rgb565_utilization_synth.pb }
