# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/ZyboIP/general_ip/ieee754_fp_to_uint/ieee754_fp_to_uint.cache/wt [current_project]
set_property parent.project_path C:/ZyboIP/general_ip/ieee754_fp_to_uint/ieee754_fp_to_uint.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths c:/ZyboIP/general_ip/ieee754_fp_to_uint/ieee754_fp_to_uint.srcs/sources_1/new [current_project]
set_property ip_output_repo c:/ZyboIP/general_ip/ieee754_fp_to_uint/ieee754_fp_to_uint.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/ZyboIP/general_ip/ieee754_fp_to_uint/ieee754_fp_to_uint.srcs/sources_1/new/ieee754_fp_to_uint.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ieee754_fp_to_uint -part xc7z010clg400-1


write_checkpoint -force -noxdef ieee754_fp_to_uint.dcp

catch { report_utilization -file ieee754_fp_to_uint_utilization_synth.rpt -pb ieee754_fp_to_uint_utilization_synth.pb }
