# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Users/Rob/Documents/Class/ECEC662/zybo-toolbox/video_processing_examples/video_passthrough_vga/video_passthrough_vga.srcs/constraints_1/ZYBO_Master.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_vga_color_test_0_0/system_vga_color_test_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga_color_test_0_0 || ORIG_REF_NAME==system_vga_color_test_0_0}]

# IP: bd/system/ip/system_vga_sync_0_0/system_vga_sync_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga_sync_0_0 || ORIG_REF_NAME==system_vga_sync_0_0}]

# IP: bd/system/ip/system_zybo_vga_0_0/system_zybo_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_zybo_vga_0_0 || ORIG_REF_NAME==system_zybo_vga_0_0}]

# IP: bd/system/ip/system_rgb888_to_rgb565_0_0/system_rgb888_to_rgb565_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgb888_to_rgb565_0_0 || ORIG_REF_NAME==system_rgb888_to_rgb565_0_0}]

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}]

# IP: bd/system/ip/system_inverter_0_0/system_inverter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_inverter_0_0 || ORIG_REF_NAME==system_inverter_0_0}]

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
