# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/affine_block/affine_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block || ORIG_REF_NAME==affine_block}]

# IP: bd/affine_block/ip/affine_block_uint_to_ieee754_fp_0_0/affine_block_uint_to_ieee754_fp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_uint_to_ieee754_fp_0_0 || ORIG_REF_NAME==affine_block_uint_to_ieee754_fp_0_0}]

# IP: bd/affine_block/ip/affine_block_uint_to_ieee754_fp_0_1/affine_block_uint_to_ieee754_fp_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_uint_to_ieee754_fp_0_1 || ORIG_REF_NAME==affine_block_uint_to_ieee754_fp_0_1}]

# IP: bd/affine_block/ip/affine_block_ieee754_fp_multiplier_0_0/affine_block_ieee754_fp_multiplier_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_0_0 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_0_0}]

# IP: bd/affine_block/ip/affine_block_ieee754_fp_multiplier_1_0/affine_block_ieee754_fp_multiplier_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_1_0 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_1_0}]

# IP: bd/affine_block/ip/affine_block_ieee754_fp_multiplier_1_1/affine_block_ieee754_fp_multiplier_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_1_1 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_1_1}]

# IP: bd/affine_block/ip/affine_block_ieee754_fp_multiplier_1_2/affine_block_ieee754_fp_multiplier_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_1_2 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_1_2}]

# IP: bd/affine_block/ip/affine_block_ieee754_fp_adder_subtractor_0_0/affine_block_ieee754_fp_adder_subtractor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_0 || ORIG_REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_0}]

# IP: bd/affine_block/ip/affine_block_ieee754_fp_adder_subtractor_0_1/affine_block_ieee754_fp_adder_subtractor_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_1 || ORIG_REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_1}]

# IP: bd/affine_block/ip/affine_block_ieee754_fp_to_uint_0_0/affine_block_ieee754_fp_to_uint_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_to_uint_0_0 || ORIG_REF_NAME==affine_block_ieee754_fp_to_uint_0_0}]

# IP: bd/affine_block/ip/affine_block_ieee754_fp_to_uint_0_1/affine_block_ieee754_fp_to_uint_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_to_uint_0_1 || ORIG_REF_NAME==affine_block_ieee754_fp_to_uint_0_1}]

# XDC: bd/affine_block/affine_block_ooc.xdc
