# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/system_affine_transform_0_1.xci
# IP: The module: 'system_affine_transform_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_uint_to_ieee754_fp_0_0/affine_block_uint_to_ieee754_fp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_uint_to_ieee754_fp_0_0 || ORIG_REF_NAME==affine_block_uint_to_ieee754_fp_0_0}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_uint_to_ieee754_fp_0_1/affine_block_uint_to_ieee754_fp_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_uint_to_ieee754_fp_0_1 || ORIG_REF_NAME==affine_block_uint_to_ieee754_fp_0_1}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_multiplier_0_0/affine_block_ieee754_fp_multiplier_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_0_0 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_0_0}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_multiplier_1_0/affine_block_ieee754_fp_multiplier_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_1_0 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_1_0}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_multiplier_1_1/affine_block_ieee754_fp_multiplier_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_1_1 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_1_1}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_multiplier_1_2/affine_block_ieee754_fp_multiplier_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_1_2 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_1_2}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_adder_subtractor_0_0/affine_block_ieee754_fp_adder_subtractor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_0 || ORIG_REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_0}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_adder_subtractor_0_1/affine_block_ieee754_fp_adder_subtractor_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_1 || ORIG_REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_1}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_to_uint_0_0/affine_block_ieee754_fp_to_uint_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_to_uint_0_0 || ORIG_REF_NAME==affine_block_ieee754_fp_to_uint_0_0}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_to_uint_0_1/affine_block_ieee754_fp_to_uint_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_to_uint_0_1 || ORIG_REF_NAME==affine_block_ieee754_fp_to_uint_0_1}]

# XDC: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/affine_block_ooc.xdc

# IP: C:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/system_affine_transform_0_1.xci
# IP: The module: 'system_affine_transform_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_uint_to_ieee754_fp_0_0/affine_block_uint_to_ieee754_fp_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_uint_to_ieee754_fp_0_0 || ORIG_REF_NAME==affine_block_uint_to_ieee754_fp_0_0}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_uint_to_ieee754_fp_0_1/affine_block_uint_to_ieee754_fp_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_uint_to_ieee754_fp_0_1 || ORIG_REF_NAME==affine_block_uint_to_ieee754_fp_0_1}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_multiplier_0_0/affine_block_ieee754_fp_multiplier_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_0_0 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_0_0}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_multiplier_1_0/affine_block_ieee754_fp_multiplier_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_1_0 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_1_0}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_multiplier_1_1/affine_block_ieee754_fp_multiplier_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_1_1 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_1_1}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_multiplier_1_2/affine_block_ieee754_fp_multiplier_1_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_multiplier_1_2 || ORIG_REF_NAME==affine_block_ieee754_fp_multiplier_1_2}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_adder_subtractor_0_0/affine_block_ieee754_fp_adder_subtractor_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_0 || ORIG_REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_0}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_adder_subtractor_0_1/affine_block_ieee754_fp_adder_subtractor_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_1 || ORIG_REF_NAME==affine_block_ieee754_fp_adder_subtractor_0_1}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_to_uint_0_0/affine_block_ieee754_fp_to_uint_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_to_uint_0_0 || ORIG_REF_NAME==affine_block_ieee754_fp_to_uint_0_0}]

# IP: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/ip/affine_block_ieee754_fp_to_uint_0_1/affine_block_ieee754_fp_to_uint_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==affine_block_ieee754_fp_to_uint_0_1 || ORIG_REF_NAME==affine_block_ieee754_fp_to_uint_0_1}]

# XDC: c:/ZyboIP/examples/affine_transform_demo/affine_transform_demo.srcs/sources_1/bd/system/ip/system_affine_transform_0_1/affine_block_ooc.xdc
