# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rob/Documents/Class/ECEC662/Zybo-Open-Source-Video-IP-Toolbox/general_ip/inverter/inverter.cache/wt [current_project]
set_property parent.project_path /home/rob/Documents/Class/ECEC662/Zybo-Open-Source-Video-IP-Toolbox/general_ip/inverter/inverter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib /home/rob/Documents/Class/ECEC662/Zybo-Open-Source-Video-IP-Toolbox/general_ip/inverter/inverter.srcs/sources_1/new/inverter.vhd
synth_design -top inverter -part xc7z010clg400-1
write_checkpoint -noxdef inverter.dcp
catch { report_utilization -file inverter_utilization_synth.rpt -pb inverter_utilization_synth.pb }
